name: 'Python Lint'
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8

      - name: Run flake8
        run: |
          cd backend
          flake8
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt pylint

      - name: Run pylint
        run: |
          cd backend
          pylint $(find . -type f -name "*.py")
